services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - .:/var/www/html
    image: nginx:alpine
    ports:
      - "8080:8080"
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - internal

networks:
  internal:
    driver: bridge